export const homeObjOne = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Znajdź odpowiedź na konkretne pytanie',
  description: '',
  buttonLabel: 'Mam pytanie...',
  imgStart: '',
  img: require('../../images/svg-1.svg').default,
  alt: 'Credit Card',
  start: '',
  linkTo: '/post/create',
  hasButton: true,
};

export const homeObjTwo = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  headline: 'Dostępność serwisu wszędzie i zawsze',
  buttonLabel: 'Zarejestować się',
  imgStart: '',
  img: require('../../images/svg-2.svg').default,
  alt: 'Vault',
  start: '',
  linkTo: '/register',
  hasButton: true,
};

export const homeObjThree = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  headline: 'Pomagaj innym w rozwiązywaniu pytań',
  buttonLabel: 'Nie ma sprawy!',
  imgStart: 'start',
  img: require('../../images/svg-4.svg').default,
  alt: 'Vault',
  start: '',
  linkTo: '/login',
  hasButton: true,
};

export const homeObjFour = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  headline: 'Szybko, łatwo i efektywnie ',
  buttonLabel: 'Czego oczekujesz?',
  imgStart: 'start',
  img: require('../../images/svg-3.svg').default,
  alt: 'Vault',
  start: 'true',
  linkTo: '/login',
  hasButton: true,
};

export const aboutObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'W trakcie',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/svg-8.svg').default,
  alt: 'Vault',
  linkTo: '/',
  hasButton: true,
};

export const regulationsObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: '',
  description: '',
  buttonLabel: 'Pobierz regulamin',
  imgStart: 'start',
  img: require('../../images/terms.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: true,
};

export const dashboardNoDataObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Nie znaleziono żadnej pubikacji :(',
  description: '',
  buttonLabel: 'Stwóż publikacje',
  imgStart: 'start',
  img: require('../../images/svg-4.svg').default,
  alt: '',
  linkTo: '/post/create',
  hasButton: true,
};

export const dashboardLandingObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Witamy! Zacznij wyszukiwanie powyżej :)',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/svg-5.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: false,
};

export const notFoundObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Błąd 404! Nie znaleziono takiej strony',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/404.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: true,
};

export const notAuthObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Brak uprawnień!',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/secure.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: true,
};

export const noPostObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Nie znaleziono odpowiedniego postu!',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/no-post.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: true,
};

export const noRepliesObj = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Brak odpowiedzi dla tej publikacji :(',
  description: '',
  buttonLabel: 'Przejdź na główną',
  imgStart: 'start',
  img: require('../../images/no-post.svg').default,
  alt: '',
  linkTo: '/',
  hasButton: false,
};
